name: "Website Deployment"

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  # Pushes files in 'website' folder to S3 bucket
  deploy:
    name: "Push to AWS S3"
    runs-on: self-hosted
    #needs: [terraform_build]  #, sonarcloud_sast]
    env:
      DOMAIN: ${{ vars.TF_SITE_DOMAIN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup AWS CLI"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: "Sync files to S3 bucket"
        run: |
          aws s3 sync website/ s3://$DOMAIN --delete

  # Runs OWASP ZAP Scan for web vulnerabilities
  zap_scan:
    runs-on: ubuntu-latest
    needs: deploy
    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://${{ vars.TF_SITE_DOMAIN }}/'
          rules_file_name: '.zap/rules.zap'
          cmd_options: '-a'

  # Runs Smoke Test with Playwright
  playwright_test:
    timeout-minutes: 60
    runs-on: self-hosted
    needs: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
